version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     # build image
     - run: |         
         docker info
         docker build -t aspnetapp -f DockerApp .
     # deploy the image
     - run: |         
         docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
         docker tag aspnetapp registry.heroku.com/$HEROKU_APP_NAME/web
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:login
         heroku container:push web --app=$HEROLU_APP_NAME
         heroku container:release web --app=$HEROLU_APP_NAME